name: "S3 Sync"
description: "Sync a directory to an AWS S3 repository"
author: fmichonneau
runs:
  using: docker
  image: Dockerfile
output:
  action_log:
    description: "log of the s3 sync command"
